package lp2projeto;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import DAO.AcompanhanteDATA;
import ModeloBD.AcompanhanteBD;
import java.util.Date;


public class Fr_acompanhante extends javax.swing.JFrame {
    private AcompanhanteBD RegAcompanhante = new AcompanhanteBD();
    private AcompanhanteDATA AcompanhanteDAO =  new AcompanhanteDATA ();
    public Fr_acompanhante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jRadioButton1 = new javax.swing.JRadioButton();
        lb_nm_acomp = new javax.swing.JLabel();
        lb_snm_acomp = new javax.swing.JLabel();
        lb_cpf_acomp = new javax.swing.JLabel();
        lb_rg_acomp = new javax.swing.JLabel();
        lb_sexo_acomp = new javax.swing.JLabel();
        lb_email_acomp = new javax.swing.JLabel();
        lb_dt_nasc_acomp = new javax.swing.JLabel();
        tf_acompNm = new javax.swing.JTextField();
        tf_acompSnm = new javax.swing.JTextField();
        tf_acompCPF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_acompRG = new javax.swing.JTextField();
        br_acompMasc = new javax.swing.JRadioButton();
        br_acompFemi = new javax.swing.JRadioButton();
        tf_acompEmail = new javax.swing.JTextField();
        bt_acompLimpar = new javax.swing.JButton();
        bt_acompSalvar = new javax.swing.JButton();
        bt_acompMenu = new javax.swing.JButton();
        cb_AcompDtnasci = new javax.swing.JComboBox<>();
        cb_acompMesNasc = new javax.swing.JComboBox<>();
        cb_acompAnonasc = new javax.swing.JComboBox<>();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_nm_acomp.setText("Nome:");

        lb_snm_acomp.setText("Sobrenome:");

        lb_cpf_acomp.setText("CPF:");

        lb_rg_acomp.setText("RG:");

        lb_sexo_acomp.setText("Sexo:");

        lb_email_acomp.setText("E-mail:");

        lb_dt_nasc_acomp.setText("Data de nascimento:");

        jLabel9.setText("Acompanhante");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        br_acompMasc.setText("Masculino");
        br_acompMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_acompMascActionPerformed(evt);
            }
        });

        br_acompFemi.setText("Feminino");
        br_acompFemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                br_acompFemiActionPerformed(evt);
            }
        });

        bt_acompLimpar.setText("Limpar");
        bt_acompLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acompLimparActionPerformed(evt);
            }
        });

        bt_acompSalvar.setText("Incluir");
        bt_acompSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acompSalvarActionPerformed(evt);
            }
        });

        bt_acompMenu.setText("Menu Principal");
        bt_acompMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_acompMenuActionPerformed(evt);
            }
        });

        cb_AcompDtnasci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        cb_AcompDtnasci.setSelectedIndex(-1);

        cb_acompMesNasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro" }));
        cb_acompMesNasc.setSelectedIndex(-1);

        cb_acompAnonasc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901" }));
        cb_acompAnonasc.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_nm_acomp)
                            .addComponent(lb_snm_acomp)
                            .addComponent(lb_cpf_acomp)
                            .addComponent(lb_rg_acomp)
                            .addComponent(lb_sexo_acomp))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_acompSnm)
                            .addComponent(tf_acompCPF)
                            .addComponent(tf_acompRG)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(br_acompMasc)
                                .addGap(60, 60, 60)
                                .addComponent(br_acompFemi))
                            .addComponent(tf_acompNm, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(bt_acompLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(bt_acompSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bt_acompMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lb_dt_nasc_acomp)
                                .addGap(40, 40, 40))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lb_email_acomp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cb_AcompDtnasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_acompMesNasc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cb_acompAnonasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_acompEmail))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nm_acomp)
                    .addComponent(tf_acompNm, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_acompSnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_snm_acomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_acompCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_cpf_acomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_acompRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_rg_acomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(br_acompMasc)
                    .addComponent(br_acompFemi)
                    .addComponent(lb_sexo_acomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_acompEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_email_acomp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dt_nasc_acomp)
                    .addComponent(cb_AcompDtnasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_acompMesNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_acompAnonasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_acompLimpar)
                    .addComponent(bt_acompSalvar))
                .addGap(18, 18, 18)
                .addComponent(bt_acompMenu)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void br_acompMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_acompMascActionPerformed
    br_acompFemi.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_br_acompMascActionPerformed

    private void bt_acompLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acompLimparActionPerformed
    LimparCampos();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_acompLimparActionPerformed

    private void bt_acompSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acompSalvarActionPerformed
    ConsisteCamposPreenchidos();
        if (TrataCampos()){
            setModelo();
            GravaDados();
            LimparCampos();
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_acompSalvarActionPerformed

    private void br_acompFemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_br_acompFemiActionPerformed
    br_acompMasc.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_br_acompFemiActionPerformed

    private void bt_acompMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_acompMenuActionPerformed
    Fr_menu localMenu = new Fr_menu ();
    localMenu.setVisible(true);
    this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_acompMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fr_acompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fr_acompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fr_acompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fr_acompanhante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fr_acompanhante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton br_acompFemi;
    private javax.swing.JRadioButton br_acompMasc;
    private javax.swing.JButton bt_acompLimpar;
    private javax.swing.JButton bt_acompMenu;
    private javax.swing.JButton bt_acompSalvar;
    private javax.swing.JComboBox<String> cb_AcompDtnasci;
    private javax.swing.JComboBox<String> cb_acompAnonasc;
    private javax.swing.JComboBox<String> cb_acompMesNasc;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_cpf_acomp;
    private javax.swing.JLabel lb_dt_nasc_acomp;
    private javax.swing.JLabel lb_email_acomp;
    private javax.swing.JLabel lb_nm_acomp;
    private javax.swing.JLabel lb_rg_acomp;
    private javax.swing.JLabel lb_sexo_acomp;
    private javax.swing.JLabel lb_snm_acomp;
    private javax.swing.JTextField tf_acompCPF;
    private javax.swing.JTextField tf_acompEmail;
    private javax.swing.JTextField tf_acompNm;
    private javax.swing.JTextField tf_acompRG;
    private javax.swing.JTextField tf_acompSnm;
    // End of variables declaration//GEN-END:variables

    private long acompCPF;
    private String acompEmail;
    private String acompNm;
    private int acompRG;
    private String acompSnm;
    private int acompAnonasc;
    private String acompMesNasc; 
    private int acompDianasci;
    private String acompSexo;
    
    //private ModeloProjeto mod;
    //private Modelo mod = new Modelo ();
    //public ArrayList<ModeloProjeto> Lista = new ArrayList();
    
    
    
private void LimparCampos(){
    tf_acompCPF.setText(null);
    tf_acompEmail.setText(null);
    tf_acompNm.setText(null);
    tf_acompRG.setText(null);      
    tf_acompSnm.setText(null);
    cb_AcompDtnasci.setSelectedIndex(-1);
    cb_acompAnonasc.setSelectedIndex(-1);
    cb_acompMesNasc.setSelectedIndex(-1);
    br_acompFemi.setSelected(false);
    br_acompMasc.setSelected(false);
}
        
    

    public void setModelo() {
        //RegAcompanhante = new ModeloProjeto ();
        RegAcompanhante.setCPF_acompanhante(acompCPF);
        RegAcompanhante.setEmail_acompanhante(acompEmail);
        RegAcompanhante.setNome_acompanhante(acompNm);
        RegAcompanhante.setRg_acompanhante(acompRG);
        RegAcompanhante.setSobrenome_acompanhante(acompSnm);
        RegAcompanhante.setSexo_acompanhante(acompSexo); 
        RegAcompanhante.setAcompAnonasc(acompAnonasc);
        RegAcompanhante.setAcompDianasci(acompDianasci);
        RegAcompanhante.setAcompMesNasc(acompMesNasc);
        
    }
    
private void GravaDados(){
        try {
            AcompanhanteDAO.Incluir(RegAcompanhante);
            JOptionPane.showMessageDialog(rootPane, "Dados Gravados com Sucesso!!!","Mensagem",JOptionPane.PLAIN_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(Fr_quarto.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    

    
    public boolean TrataCampos() {
    boolean retorno = false;
    try {
        acompNm = tf_acompNm.getText().trim();
        acompSnm = tf_acompSnm.getText().trim();
        acompEmail = tf_acompEmail.getText().trim();
        
        acompCPF = Long.parseLong(tf_acompCPF.getText().trim());
        acompRG = Integer.parseInt(tf_acompRG.getText().trim());
        
        acompMesNasc = cb_acompMesNasc.getItemAt(cb_acompMesNasc.getSelectedIndex());
        acompDianasci = cb_AcompDtnasci.getSelectedIndex();
        acompAnonasc = cb_acompAnonasc.getSelectedIndex();
        
       if(br_acompFemi.isSelected()) acompSexo=("F"); else acompSexo=("M");
       retorno = true;
        }
    catch (NumberFormatException erro) {
        JOptionPane.showMessageDialog(null, "CPF e RG devem ser campos numéricos","Erro",JOptionPane.ERROR_MESSAGE);
    }
    return retorno;
}
    
    
    public void ConsisteCamposPreenchidos() {
    if (tf_acompNm.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha o Nome!","Erro",JOptionPane.ERROR_MESSAGE);
    }
    if (tf_acompSnm.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Preencha o Sobrenome!","Erro",JOptionPane.ERROR_MESSAGE);
    }
    if(tf_acompCPF.getText().trim().isEmpty()) {
     JOptionPane.showMessageDialog(null, "Preencha o CPF!","Erro",JOptionPane.ERROR_MESSAGE);   
    }
    if(tf_acompEmail.getText().trim().isEmpty()) {
      JOptionPane.showMessageDialog(null, "Preencha o Email!","Erro",JOptionPane.ERROR_MESSAGE);  
    }
    if((!br_acompFemi.isSelected())&&(!br_acompMasc.isSelected())){
        JOptionPane.showMessageDialog(null, "Selecione o Sexo!","Erro",JOptionPane.ERROR_MESSAGE);
    }
    if(cb_acompAnonasc.getSelectedIndex()==-1) {
        JOptionPane.showMessageDialog(null, "Selecione o ano de nascimento","Erro",JOptionPane.ERROR_MESSAGE);
    }
    if(cb_AcompDtnasci.getSelectedIndex()==-1) {
        JOptionPane.showMessageDialog(null, "Selecione a data de nascimento","Erro",JOptionPane.ERROR_MESSAGE);
    }
    if(cb_acompMesNasc.getSelectedIndex()==-1) {
        JOptionPane.showMessageDialog(null, "Selecione o mês de nascimento","Erro",JOptionPane.ERROR_MESSAGE);
    }

}

    private String Date(String trim) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
