/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lp2projeto;

import javax.swing.JOptionPane;

/**
 *
 * @author burtonm
 */
public class Fr_menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Fr_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        bt_reserva = new javax.swing.JButton();
        bt_cliente = new javax.swing.JButton();
        bt_produto = new javax.swing.JButton();
        lb_imagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuAcompanhante = new javax.swing.JMenuItem();
        jMenuHospedagem = new javax.swing.JMenuItem();
        jMenuProdSer = new javax.swing.JMenuItem();
        jMenuQuarto = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        bt_reserva.setText("Hospedagem");
        bt_reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reservaActionPerformed(evt);
            }
        });
        getContentPane().add(bt_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 120, -1));

        bt_cliente.setText("Cliente");
        bt_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(bt_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 90, -1));

        bt_produto.setText("Produtos & Serviços");
        bt_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_produtoActionPerformed(evt);
            }
        });
        getContentPane().add(bt_produto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        lb_imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/imagem-do-hotel.png"))); // NOI18N
        getContentPane().add(lb_imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 559));

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCliente);

        jMenuAcompanhante.setText("Acompanhante");
        jMenuAcompanhante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAcompanhanteActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuAcompanhante);

        jMenuHospedagem.setText("Hospedagem");
        jMenuHospedagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHospedagemActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuHospedagem);

        jMenuProdSer.setText("Produtos e Serviços");
        jMenuProdSer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdSerActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuProdSer);

        jMenuQuarto.setText("Quarto");
        jMenuQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuartoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuQuarto);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Hospedagem");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
    Fr_cliente localCliente = new Fr_cliente ();
    localCliente.setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuHospedagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHospedagemActionPerformed
    Fr_hospedagem localHosp = new Fr_hospedagem ();
    localHosp.setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuHospedagemActionPerformed

    private void jMenuProdSerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdSerActionPerformed
    Fr_produto localProd = new Fr_produto ();
    localProd.setVisible(true);  
    this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuProdSerActionPerformed

    private void jMenuAcompanhanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAcompanhanteActionPerformed
     Fr_acompanhante localAcomp = new Fr_acompanhante ();
    localAcomp.setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAcompanhanteActionPerformed

    private void jMenuQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuartoActionPerformed
    Fr_quarto localQuarto = new Fr_quarto ();
    localQuarto.setVisible(true);
    this.dispose();
    // TODO add your handling code here:
    }//GEN-LAST:event_jMenuQuartoActionPerformed

    private void bt_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_clienteActionPerformed
        Fr_cliente c = new Fr_cliente();
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_clienteActionPerformed

    private void bt_reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reservaActionPerformed
        Fr_hospedagem h = new Fr_hospedagem();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_reservaActionPerformed

    private void bt_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_produtoActionPerformed
        Fr_produto p = new Fr_produto();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bt_produtoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fr_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fr_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fr_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fr_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fr_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cliente;
    private javax.swing.JButton bt_produto;
    private javax.swing.JButton bt_reserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuAcompanhante;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuHospedagem;
    private javax.swing.JMenuItem jMenuProdSer;
    private javax.swing.JMenuItem jMenuQuarto;
    private javax.swing.JLabel lb_imagem;
    // End of variables declaration//GEN-END:variables

    
}